--liquibase formatted sql

--changeset gamesphere:001-create-core-schema

CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                       name VARCHAR(255) NOT NULL,
                       CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                       username VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       first_name VARCHAR(255),
                       last_name VARCHAR(255),
                       avatar_url VARCHAR(255),
                       phone_number VARCHAR(255),
                       address VARCHAR(255),
                       is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
                       is_seller BOOLEAN NOT NULL DEFAULT FALSE,
                       balance DOUBLE PRECISION NOT NULL DEFAULT 0,
                       CONSTRAINT uk_users_username UNIQUE (username),
                       CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
                            CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                            CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE seller_profiles (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                 updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                 is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                                 user_id BIGINT NOT NULL,
                                 shop_name VARCHAR(255),
                                 bio VARCHAR(1000),
                                 contact_email VARCHAR(255),
                                 phone_number VARCHAR(255),
                                 is_approved BOOLEAN NOT NULL DEFAULT FALSE,
                                 CONSTRAINT uk_seller_profiles_user UNIQUE (user_id),
                                 CONSTRAINT uk_seller_profiles_shop_name UNIQUE (shop_name),
                                 CONSTRAINT fk_seller_profiles_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE games (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                       title VARCHAR(255) NOT NULL,
                       slug VARCHAR(255) NOT NULL,
                       description VARCHAR(2000),
                       cover_image_url VARCHAR(255),
                       developer VARCHAR(255),
                       publisher VARCHAR(255),
                       release_date DATE,
                       CONSTRAINT uk_games_slug UNIQUE (slug)
);

CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                            is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                            name VARCHAR(255) NOT NULL,
                            description VARCHAR(255),
                            CONSTRAINT uk_categories_name UNIQUE (name)
);

--rollback DROP TABLE IF EXISTS categories;
--rollback DROP TABLE IF EXISTS games;
--rollback DROP TABLE IF EXISTS seller_profiles;
--rollback DROP TABLE IF EXISTS user_roles;
--rollback DROP TABLE IF EXISTS users;
--rollback DROP TABLE IF EXISTS roles;