--liquibase formatted sql

--changeset gamesphere:002-create-catalog-schema

CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                          updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                          is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                          name VARCHAR(255) NOT NULL,
                          slug VARCHAR(255) NOT NULL,
                          description VARCHAR(2000),
                          price NUMERIC(38, 2) NOT NULL,
                          discount_price NUMERIC(38, 2),
                          stock_quantity INTEGER NOT NULL,
                          platform VARCHAR(255) NOT NULL,
                          genre VARCHAR(255),
                          image_url VARCHAR(255),
                          key_provider VARCHAR(255),
                          store_name VARCHAR(255),
                          store_url VARCHAR(1000),
                          delivery_type VARCHAR(255) NOT NULL DEFAULT 'STORE_REDIRECT',
                          redemption_url VARCHAR(1000),
                          requires_player_id BOOLEAN NOT NULL DEFAULT FALSE,
                          player_id_label VARCHAR(255),
                          redemption_instructions VARCHAR(1000),
                          in_game_currency_name VARCHAR(255),
                          in_game_amount INTEGER,
                          bonus_amount INTEGER,
                          region VARCHAR(255) NOT NULL DEFAULT 'GLOBAL',
                          currency VARCHAR(255) NOT NULL DEFAULT 'USD',
                          official_store BOOLEAN NOT NULL DEFAULT FALSE,
                          last_checked_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                          game_id BIGINT,
                          product_type VARCHAR(255) NOT NULL DEFAULT 'GAME',
                          product_status VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
                          seller_id BIGINT,
                          is_active BOOLEAN NOT NULL DEFAULT TRUE,
                          CONSTRAINT uk_products_slug UNIQUE (slug),
                          CONSTRAINT ck_products_price_non_negative CHECK (price >= 0),
                          CONSTRAINT ck_products_discount_non_negative CHECK (discount_price IS NULL OR discount_price >= 0),
                          CONSTRAINT ck_products_discount_not_above_price CHECK (discount_price IS NULL OR discount_price <= price),
                          CONSTRAINT ck_products_stock_non_negative CHECK (stock_quantity >= 0),
                          CONSTRAINT ck_products_in_game_amount_positive CHECK (in_game_amount IS NULL OR in_game_amount > 0),
                          CONSTRAINT ck_products_bonus_non_negative CHECK (bonus_amount IS NULL OR bonus_amount >= 0),
                          CONSTRAINT fk_products_game FOREIGN KEY (game_id) REFERENCES games (id),
                          CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users (id)
);

CREATE TABLE product_categories (
                                    product_id BIGINT NOT NULL,
                                    category_id BIGINT NOT NULL,
                                    CONSTRAINT pk_product_categories PRIMARY KEY (product_id, category_id),
                                    CONSTRAINT fk_product_categories_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
                                    CONSTRAINT fk_product_categories_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);

CREATE TABLE product_images (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                                product_id BIGINT NOT NULL,
                                image_url VARCHAR(255) NOT NULL,
                                sort_order INTEGER NOT NULL DEFAULT 0,
                                is_primary BOOLEAN NOT NULL DEFAULT FALSE,
                                CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

--rollback DROP TABLE IF EXISTS product_images;
--rollback DROP TABLE IF EXISTS product_categories;
--rollback DROP TABLE IF EXISTS products;