--liquibase formatted sql

--changeset gamesphere:003-create-commerce-schema

CREATE TABLE carts (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                       user_id BIGINT NOT NULL,
                       CONSTRAINT uk_carts_user UNIQUE (user_id),
                       CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE cart_items (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                            is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                            cart_id BIGINT NOT NULL,
                            product_id BIGINT NOT NULL,
                            quantity INTEGER NOT NULL,
                            price_at_add_time NUMERIC(38, 2),
                            CONSTRAINT uk_cart_items_cart_product UNIQUE (cart_id, product_id),
                            CONSTRAINT ck_cart_items_quantity_positive CHECK (quantity > 0),
                            CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
                            CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE wishlists (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                           updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                           is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                           user_id BIGINT NOT NULL,
                           CONSTRAINT uk_wishlists_user UNIQUE (user_id),
                           CONSTRAINT fk_wishlists_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE wishlist_items (
                                wishlist_id BIGINT NOT NULL,
                                product_id BIGINT NOT NULL,
                                CONSTRAINT pk_wishlist_items PRIMARY KEY (wishlist_id, product_id),
                                CONSTRAINT fk_wishlist_items_wishlist FOREIGN KEY (wishlist_id) REFERENCES wishlists (id) ON DELETE CASCADE,
                                CONSTRAINT fk_wishlist_items_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                        user_id BIGINT NOT NULL,
                        order_number VARCHAR(255) NOT NULL,
                        status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
                        total_amount NUMERIC(38, 2) NOT NULL,
                        discount_amount NUMERIC(38, 2) NOT NULL DEFAULT 0,
                        payment_method VARCHAR(255),
                        transaction_id VARCHAR(255),
                        CONSTRAINT uk_orders_order_number UNIQUE (order_number),
                        CONSTRAINT ck_orders_total_non_negative CHECK (total_amount >= 0),
                        CONSTRAINT ck_orders_discount_non_negative CHECK (discount_amount >= 0),
                        CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                             updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                             is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                             order_id BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             quantity INTEGER NOT NULL,
                             price_at_purchase NUMERIC(38, 2) NOT NULL,
                             gift BOOLEAN NOT NULL DEFAULT FALSE,
                             gift_recipient_email VARCHAR(255),
                             gift_message VARCHAR(500),
                             CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0),
                             CONSTRAINT ck_order_items_price_non_negative CHECK (price_at_purchase >= 0),
                             CONSTRAINT ck_order_items_gift_recipient CHECK (gift = FALSE OR gift_recipient_email IS NOT NULL),
                             CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
                             CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE payments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                          updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                          is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                          order_id BIGINT NOT NULL,
                          user_id BIGINT NOT NULL,
                          amount NUMERIC(38, 2) NOT NULL,
                          method VARCHAR(255) NOT NULL,
                          status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
                          transaction_id VARCHAR(255) NOT NULL,
                          full_name VARCHAR(255),
                          country VARCHAR(255),
                          city VARCHAR(255),
                          billing_email VARCHAR(255),
                          tax_number VARCHAR(255),
                          CONSTRAINT uk_payments_order UNIQUE (order_id),
                          CONSTRAINT uk_payments_transaction UNIQUE (transaction_id),
                          CONSTRAINT ck_payments_amount_non_negative CHECK (amount >= 0),
                          CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id),
                          CONSTRAINT fk_payments_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE gifts (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                       sender_id BIGINT NOT NULL,
                       recipient_user_id BIGINT,
                       recipient_email VARCHAR(255) NOT NULL,
                       product_id BIGINT NOT NULL,
                       order_item_id BIGINT NOT NULL,
                       message VARCHAR(500),
                       claim_token VARCHAR(255) NOT NULL,
                       status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
                       claimed_at TIMESTAMP WITHOUT TIME ZONE,
                       expires_at TIMESTAMP WITHOUT TIME ZONE,
                       CONSTRAINT uk_gifts_claim_token UNIQUE (claim_token),
                       CONSTRAINT fk_gifts_sender FOREIGN KEY (sender_id) REFERENCES users (id),
                       CONSTRAINT fk_gifts_recipient FOREIGN KEY (recipient_user_id) REFERENCES users (id),
                       CONSTRAINT fk_gifts_product FOREIGN KEY (product_id) REFERENCES products (id),
                       CONSTRAINT fk_gifts_order_item FOREIGN KEY (order_item_id) REFERENCES order_items (id)
);

CREATE TABLE user_entitlements (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                   updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                   is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                                   user_id BIGINT NOT NULL,
                                   product_id BIGINT NOT NULL,
                                   order_item_id BIGINT NOT NULL,
                                   status VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
                                   granted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                   CONSTRAINT uk_user_entitlement_product UNIQUE (user_id, product_id),
                                   CONSTRAINT fk_user_entitlements_user FOREIGN KEY (user_id) REFERENCES users (id),
                                   CONSTRAINT fk_user_entitlements_product FOREIGN KEY (product_id) REFERENCES products (id),
                                   CONSTRAINT fk_user_entitlements_order_item FOREIGN KEY (order_item_id) REFERENCES order_items (id)
);

--rollback DROP TABLE IF EXISTS user_entitlements;
--rollback DROP TABLE IF EXISTS gifts;
--rollback DROP TABLE IF EXISTS payments;
--rollback DROP TABLE IF EXISTS order_items;
--rollback DROP TABLE IF EXISTS orders;
--rollback DROP TABLE IF EXISTS wishlist_items;
--rollback DROP TABLE IF EXISTS wishlists;
--rollback DROP TABLE IF EXISTS cart_items;
--rollback DROP TABLE IF EXISTS carts;