--liquibase formatted sql

--changeset gamesphere:004-create-community-schema

CREATE TABLE notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                               updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                               is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                               user_id BIGINT NOT NULL,
                               type VARCHAR(255) NOT NULL,
                               status VARCHAR(255) NOT NULL DEFAULT 'UNREAD',
                               title VARCHAR(255) NOT NULL,
                               message VARCHAR(1000),
                               CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE reviews (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                         updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                         is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                         product_id BIGINT NOT NULL,
                         user_id BIGINT NOT NULL,
                         rating INTEGER NOT NULL,
                         comment VARCHAR(1000),
                         approved BOOLEAN NOT NULL DEFAULT FALSE,
                         CONSTRAINT uk_reviews_product_user UNIQUE (product_id, user_id),
                         CONSTRAINT ck_reviews_rating_range CHECK (rating BETWEEN 1 AND 5),
                         CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
                         CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE tournaments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                             updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                             is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                             title VARCHAR(255) NOT NULL,
                             description VARCHAR(1500),
                             entry_fee NUMERIC(38, 2) NOT NULL,
                             start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                             end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                             game VARCHAR(255),
                             status VARCHAR(255) NOT NULL DEFAULT 'UPCOMING',
                             creator_id BIGINT,
                             max_participants INTEGER NOT NULL DEFAULT 0,
                             current_participants INTEGER NOT NULL DEFAULT 0,
                             prize_pool NUMERIC(38, 2),
                             CONSTRAINT ck_tournaments_dates CHECK (end_date > start_date),
                             CONSTRAINT ck_tournaments_entry_fee_non_negative CHECK (entry_fee >= 0),
                             CONSTRAINT ck_tournaments_max_participants_non_negative CHECK (max_participants >= 0),
                             CONSTRAINT ck_tournaments_current_participants_non_negative CHECK (current_participants >= 0),
                             CONSTRAINT ck_tournaments_prize_pool_non_negative CHECK (prize_pool IS NULL OR prize_pool >= 0),
                             CONSTRAINT fk_tournaments_creator FOREIGN KEY (creator_id) REFERENCES users (id)
);

CREATE TABLE tournament_participants (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                         updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                         is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                                         tournament_id BIGINT NOT NULL,
                                         user_id BIGINT NOT NULL,
                                         in_game_nickname VARCHAR(255),
                                         team_name VARCHAR(255),
                                         status VARCHAR(255) NOT NULL DEFAULT 'REGISTERED',
                                         reminder_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
                                         CONSTRAINT uk_tournament_participants_user UNIQUE (tournament_id, user_id),
                                         CONSTRAINT fk_tournament_participants_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments (id) ON DELETE CASCADE,
                                         CONSTRAINT fk_tournament_participants_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

--rollback DROP TABLE IF EXISTS tournament_participants;
--rollback DROP TABLE IF EXISTS tournaments;
--rollback DROP TABLE IF EXISTS reviews;
--rollback DROP TABLE IF EXISTS notifications;