--liquibase formatted sql

--changeset gamesphere:008-create-top-up-fulfillments
CREATE TABLE top_up_fulfillments (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                                     order_item_id BIGINT NOT NULL,
                                     status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
                                     attempt_count INTEGER NOT NULL DEFAULT 0,
                                     provider_reference VARCHAR(255),
                                     failure_reason VARCHAR(1000),
                                     last_attempt_at TIMESTAMP WITHOUT TIME ZONE,
                                     completed_at TIMESTAMP WITHOUT TIME ZONE,
                                     CONSTRAINT uk_top_up_fulfillments_order_item UNIQUE (order_item_id),
                                     CONSTRAINT ck_top_up_fulfillments_attempt_count CHECK (attempt_count >= 0),
                                     CONSTRAINT fk_top_up_fulfillments_order_item
                                         FOREIGN KEY (order_item_id) REFERENCES order_items (id) ON DELETE CASCADE
);

CREATE INDEX idx_top_up_fulfillments_status_created
    ON top_up_fulfillments (status, created_at);

--rollback DROP TABLE IF EXISTS top_up_fulfillments;