--liquibase formatted sql

--changeset gamesphere:009-add-refresh-tokens
CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                                user_id BIGINT NOT NULL,
                                token_hash VARCHAR(64) NOT NULL,
                                expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                revoked_at TIMESTAMP WITHOUT TIME ZONE,
                                replaced_by_token_hash VARCHAR(64),
                                CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
                                CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user_active
    ON refresh_tokens (user_id, revoked_at, expires_at);

--rollback DROP TABLE IF EXISTS refresh_tokens;