--liquibase formatted sql

--changeset gamesphere:010-add-digital-delivery
CREATE TABLE digital_codes (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                               updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                               is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                               product_id BIGINT NOT NULL,
                               code_value VARCHAR(500) NOT NULL,
                               status VARCHAR(255) NOT NULL DEFAULT 'AVAILABLE',
                               delivered_at TIMESTAMP WITHOUT TIME ZONE,
                               CONSTRAINT uk_digital_codes_value UNIQUE (code_value),
                               CONSTRAINT fk_digital_codes_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_digital_codes_product_status
    ON digital_codes (product_id, status, id);

ALTER TABLE user_entitlements
    ADD COLUMN digital_code_id BIGINT;

ALTER TABLE user_entitlements
    ADD CONSTRAINT uk_user_entitlements_digital_code UNIQUE (digital_code_id),
    ADD CONSTRAINT fk_user_entitlements_digital_code
        FOREIGN KEY (digital_code_id) REFERENCES digital_codes (id);

CREATE INDEX idx_user_entitlements_user_granted
    ON user_entitlements (user_id, granted_at DESC);

--rollback DROP INDEX IF EXISTS idx_user_entitlements_user_granted;
--rollback ALTER TABLE user_entitlements DROP CONSTRAINT IF EXISTS fk_user_entitlements_digital_code;
--rollback ALTER TABLE user_entitlements DROP CONSTRAINT IF EXISTS uk_user_entitlements_digital_code;
--rollback ALTER TABLE user_entitlements DROP COLUMN IF EXISTS digital_code_id;
--rollback DROP TABLE IF EXISTS digital_codes;