import { createContext, useContext, useMemo, useState } from "react";

const translations = {
    EN: {
        nav: { games: "Games", topUps: "Top-ups", marketplace: "Marketplace", tournaments: "Tournaments", search: "Search games", language: "Language", wishlist: "Wishlist", cart: "Cart", profile: "Profile", home: "GameSphere home" },
        common: { loading: "Loading...", reset: "Reset", clearAll: "Clear all", visitStore: "Visit store", unknown: "Unknown", global: "Global", offers: "offers", products: "products", games: "games", packages: "packages", from: "From", bonus: "Bonus", checked: "Checked", lowestPrice: "Lowest price", noOffers: "No offers match the selected filters.", storeUnavailable: "Store unavailable", close: "Close", cancel: "Cancel", price: "Price" },
        home: { eyebrow: "GAME PRICE COMPARISON", title: "Find the right game, on the right platform.", description: "Compare official store offers, platform editions and digital delivery options in one focused catalog.", browse: "Browse games", marketplace: "Explore marketplace", aria: "GameSphere sections", what: "WHAT YOU CAN DO", heading: "A clearer route to your next game.", compare: "Compare games", compareText: "Search by genre, platform and release year.", items: "Check marketplace items", itemsText: "Review external item markets and providers.", follow: "Follow tournaments", followText: "Keep competitive events in the same place.", featured: "Featured", featuredEyebrow: "PRICE CHECKED ACROSS STORES", comparePrices: "Compare prices", compareOffers: "Compare offers", viewOffers: "View offers", viewAll: "View all", from: "From", gameStore: "Game store", catalogEyebrow: "CATALOG", trending: "Trending games", dealsEyebrow: "SMART SHOPPING", bestDeals: "Best deals", platformEyebrow: "CHOOSE YOUR PLATFORM", browsePlatforms: "Browse by platform", tournamentEyebrow: "COMPETE", tournaments: "Live and upcoming tournaments", upcomingBadge: "Upcoming", prizePool: "prize pool", digitalEyebrow: "DIGITAL STORE", digitalStore: "Top-ups and digital products", digitalProduct: "Digital product", confirmPurchase: "Confirm purchase", continueBuy: "Continue", recharge: "Recharge game accounts", rechargeText: "Find game currency and digital packages for your favorite games." },
        games: { catalog: "Game catalog", browse: "Browse games", resultsFor: "Results for", description: "Compare platforms, current store prices and digital offers.", showing: "Showing {count} of {total} games", loading: "Loading games...", pagination: "Catalog pagination", previous: "Previous", page: "Page {current} of {total}", next: "Next", filters: "Filters", gameType: "Game type", allGames: "All games", freeToPlay: "Free to play", paid: "Paid games", genre: "Genre", allGenres: "All genres", platform: "Platform", allPlatforms: "All platforms", releaseYear: "Release year", allYears: "All years", publisher: "Publisher", publisherPlaceholder: "For example: EA", minPrice: "Min price", maxPrice: "Max price", sortBy: "Sort by", alphabetical: "Alphabetical", newest: "Newest", oldest: "Oldest", lowHigh: "Price: Low to High", highLow: "Price: High to Low", apply: "Apply filters", noResults: "No games found", tryFilters: "Try changing your filters or search term.", resetFilters: "Reset filters", viewOffers: "View offers", unknownDeveloper: "Unknown developer", unknownPublisher: "Unknown publisher", tba: "TBA", activeFilters: "Active filters", searchPrefix: "Search: {value}", fromPrice: "From ${value}", upToPrice: "Up to ${value}" },
        details: { games: "Games", loading: "Loading game...", unknownDeveloper: "Unknown developer", unknownPublisher: "Unknown publisher", noDescription: "No description is available.", refreshing: "Refreshing offers...", overview: "Game overview", readMore: "Read more", readLess: "Read less", editions: "Editions", chooseEdition: "Choose an edition", allEditions: "All editions", additionalContent: "Additional content" },
        reviews: { eyebrow: "COMMUNITY", title: "Reviews", write: "Write a review", count: "{count} reviews", rating: "Rating", comment: "Your review", submit: "Publish review", empty: "No approved reviews yet." },
        offers: { filters: "Offer filters", productType: "Product type", allProductTypes: "All product types", game: "Game", dlc: "DLC", currency: "In-game currency", item: "In-game item", battlePass: "Battle pass", subscription: "Subscription", bundle: "Bundle", storeType: "Store type", allStores: "All stores", officialStores: "Official stores", partnerStores: "Partner stores", availability: "Availability", allOffers: "All offers", inStock: "In stock", outOfStock: "Out of stock", sort: "Sort", lowest: "Lowest price", highest: "Highest price", recentlyChecked: "Recently checked", storeOffers: "Store offers", foundAcross: "{count} offers found across {platforms} platforms.", officialStore: "Official store", credits: "credits", bonus: "bonus", checked: "Checked", visitStore: "Visit store", unavailable: "Store unavailable", bestPrice: "Best price" },
        topUps: { eyebrow: "FREE-TO-PLAY ECONOMY", title: "Top-ups", description: "Compare currency, passes and digital packages for your games.", available: "{count} games available", categories: { all: "All top-ups", game: "Game top-ups", gift: "Gift cards", subscription: "Subscriptions", credit: "Digital credits" }, loading: "Loading top-ups...", emptyTitle: "No top-up products yet", emptyText: "Create an in-game currency product from Postman and it will appear here.", packageEyebrow: "TOP-UP PACKAGES", choose: "Choose a package and continue to checkout.", loadingPackages: "Loading packages...", openCatalog: "Open this page from the Top-ups catalog", packagesListed: "Packages will be listed here after the catalog is loaded.", playerId: "Player ID", buyNow: "Buy now", adding: "Adding...", addedToCart: "Added to cart.", packagesTitle: "Top-up packages", packageCount: "{count} packages", gameTopUps: "Game top-up", digitalProduct: "Digital product", confirmPurchase: "Confirm purchase", continueBuy: "Continue", },
        marketplace: { eyebrow: "DIGITAL MARKET", title: "Marketplace", description: "Compare game keys, DLC, editions, skins and digital items.", products: "{count} products", loading: "Loading marketplace...", emptyTitle: "No marketplace products yet", emptyText: "Create a marketplace product with catalogSection MARKETPLACE." },
        footer: { comparison: "Game price comparison" },
        errors: { notFound: "Page not found", returnGames: "Return to games" },
    },
    AZ: {
        nav: { games: "Oyunlar", topUps: "Balans yükləmələri", marketplace: "Marketplace", tournaments: "Turnirlər", search: "Oyun axtar", language: "Dil", wishlist: "İstək siyahısı", cart: "Səbət", profile: "Profil", home: "GameSphere ana səhifə" },
        common: { loading: "Yüklənir...", reset: "Sıfırla", clearAll: "Hamısını sil", visitStore: "Mağazaya keç", unknown: "Naməlum", global: "Qlobal", offers: "təklif", products: "məhsul", games: "oyun", packages: "paket", from: "Başlanğıc", bonus: "Bonus", checked: "Yoxlanılıb", lowestPrice: "Ən aşağı qiymət", noOffers: "Seçilmiş filtrlərə uyğun təklif yoxdur.", storeUnavailable: "Mağaza mövcud deyil", close: "Bağla", cancel: "Ləğv et", price: "Qiymət" },
        home: { eyebrow: "OYUN QİYMƏT MÜQAYİSƏSİ", title: "Düzgün platformada düzgün oyunu tap.", description: "Rəsmi mağazaları, platforma versiyalarını və rəqəmsal çatdırılma seçimlərini bir kataloqda müqayisə et.", browse: "Oyunlara bax", marketplace: "Marketplace-i kəşf et", aria: "GameSphere bölmələri", what: "NƏ EDƏ BİLƏRSƏN", heading: "Növbəti oyunun üçün daha aydın yol.", compare: "Oyunları müqayisə et", compareText: "Janr, platforma və buraxılış ilinə görə axtar.", items: "Marketplace məhsullarına bax", itemsText: "Xarici item bazarlarını və təminatçıları yoxla.", follow: "Turnirləri izlə", followText: "Rəqabətli tədbirləri bir yerdə saxla.", featured: "Seçilmiş", featuredEyebrow: "MAĞAZALARDA QİYMƏT YOXLANDI", comparePrices: "Qiymətləri müqayisə et", compareOffers: "Təklifləri müqayisə et", viewOffers: "Təkliflərə bax", viewAll: "Hamısına bax", from: "Başlanğıc qiymət", gameStore: "Oyun mağazası", catalogEyebrow: "KATALOQ", trending: "Trend oyunlar", dealsEyebrow: "AĞILLI ALIŞ-VERİŞ", bestDeals: "Ən yaxşı təkliflər", platformEyebrow: "PLATFORMANI SEÇ", browsePlatforms: "Platformaya görə bax", tournamentEyebrow: "YARIŞ", tournaments: "Canlı və gələcək turnirlər", upcomingBadge: "Gələcək", prizePool: "mükafat fondu", digitalEyebrow: "RƏQƏMSAL MAĞAZA", digitalStore: "Top-up və rəqəmsal məhsullar", digitalProduct: "Rəqəmsal məhsul", confirmPurchase: "Alışı təsdiqlə", continueBuy: "Davam et", recharge: "Oyun hesabını artır", rechargeText: "Sevdiyin oyunlar üçün oyun valyutası və rəqəmsal paketlər tap." },
        games: { catalog: "Oyun kataloqu", browse: "Oyunlara bax", resultsFor: "Nəticələr", description: "Platformaları, mağaza qiymətlərini və rəqəmsal təklifləri müqayisə et.", showing: "{total} oyundan {count} göstərilir", loading: "Oyunlar yüklənir...", pagination: "Kataloq səhifələnməsi", previous: "Əvvəlki", page: "Səhifə {current} / {total}", next: "Növbəti", filters: "Filtrlər", gameType: "Oyun tipi", allGames: "Bütün oyunlar", freeToPlay: "Pulsuz oyunlar", paid: "Ödənişli oyunlar", genre: "Janr", allGenres: "Bütün janrlar", platform: "Platforma", allPlatforms: "Bütün platformalar", releaseYear: "Buraxılış ili", allYears: "Bütün illər", publisher: "Nəşriyyatçı", publisherPlaceholder: "Məsələn: EA", minPrice: "Minimum qiymət", maxPrice: "Maksimum qiymət", sortBy: "Sıralama", alphabetical: "Əlifba sırası", newest: "Ən yeni", oldest: "Ən köhnə", lowHigh: "Qiymət: aşağıdan yuxarı", highLow: "Qiymət: yuxarıdan aşağı", apply: "Filtrləri tətbiq et", noResults: "Oyun tapılmadı", tryFilters: "Filtrləri və ya axtarış sözünü dəyiş.", resetFilters: "Filtrləri sıfırla", viewOffers: "Təkliflərə bax", unknownDeveloper: "Naməlum developer", unknownPublisher: "Naməlum nəşriyyatçı", tba: "Məlum deyil", activeFilters: "Aktiv filtrlər", searchPrefix: "Axtarış: {value}", fromPrice: "{value}$-dan", upToPrice: "{value}$-dək" },
        details: { games: "Oyunlar", loading: "Oyun yüklənir...", unknownDeveloper: "Naməlum developer", unknownPublisher: "Naməlum nəşriyyatçı", noDescription: "Açıqlama mövcud deyil.", refreshing: "Təkliflər yenilənir...", overview: "Oyun haqqında", readMore: "Daha çox oxu", readLess: "Daha az göstər", editions: "Versiyalar", chooseEdition: "Versiya seç", allEditions: "Bütün versiyalar", additionalContent: "Əlavə məzmun" },
        reviews: { eyebrow: "CƏMİYYƏT", title: "Rəylər", write: "Rəy yaz", count: "{count} rəy", rating: "Qiymət", comment: "Rəyiniz", submit: "Rəyi paylaş", empty: "Hələ təsdiqlənmiş rəy yoxdur." },
        offers: { filters: "Təklif filtrləri", productType: "Məhsul tipi", allProductTypes: "Bütün məhsul tipləri", game: "Oyun", dlc: "DLC", currency: "Oyun valyutası", item: "Oyun içi item", battlePass: "Battle pass", subscription: "Abunəlik", bundle: "Bundle", storeType: "Mağaza tipi", allStores: "Bütün mağazalar", officialStores: "Rəsmi mağazalar", partnerStores: "Tərəfdaş mağazalar", availability: "Mövcudluq", allOffers: "Bütün təkliflər", inStock: "Stokda var", outOfStock: "Stokda yoxdur", sort: "Sıralama", lowest: "Ən aşağı qiymət", highest: "Ən yüksək qiymət", recentlyChecked: "Son yoxlanılan", storeOffers: "Mağaza təklifləri", foundAcross: "{platforms} platformada {count} təklif tapıldı.", officialStore: "Rəsmi mağaza", credits: "kredit", bonus: "bonus", checked: "Yoxlanılıb", visitStore: "Mağazaya keç", unavailable: "Mağaza mövcud deyil", bestPrice: "Ən yaxşı qiymət" },
        topUps: { eyebrow: "PULSUZ OYUN İQTİSADİYYATI", title: "Balans yükləmələri", description: "Oyunların valyuta, pass və rəqəmsal paketlərini müqayisə et.", available: "{count} oyun mövcuddur", categories: { all: "Bütün yükləmələr", game: "Oyun yükləmələri", gift: "Hədiyyə kartları", subscription: "Abunəliklər", credit: "Rəqəmsal kreditlər" }, loading: "Yükləmələr yüklənir...", emptyTitle: "Hələ top-up məhsulu yoxdur", emptyText: "Postman-dan oyun valyutası məhsulu yarat və burada görünsün.", packageEyebrow: "TOP-UP PAKETLƏRİ", choose: "Paket seç və seçilmiş təminatçıya keç.", loadingPackages: "Paketlər yüklənir...", openCatalog: "Bu səhifəni Top-ups kataloqundan aç", packagesListed: "Kataloq yükləndikdən sonra paketlər burada görünəcək." },
        marketplace: { eyebrow: "RƏQƏMSAL BAZAR", title: "Marketplace", description: "Oyun açarlarını, DLC-ləri, versiyaları, skin-ləri və rəqəmsal itemləri müqayisə et.", products: "{count} məhsul", loading: "Marketplace yüklənir...", emptyTitle: "Hələ marketplace məhsulu yoxdur", emptyText: "catalogSection MARKETPLACE olan məhsul yarat." },
        footer: { comparison: "Oyun qiymət müqayisəsi" },
        errors: { notFound: "Səhifə tapılmadı", returnGames: "Oyunlara qayıt" },
    },
    TR: {},
    RU: {},
};

function mergeTranslations(base, overrides) {
    return Object.keys(base).reduce((result, key) => {
        const baseValue = base[key];
        const overrideValue = overrides[key];
        result[key] = baseValue && typeof baseValue === "object"
            ? mergeTranslations(baseValue, overrideValue || {})
            : overrideValue ?? baseValue;
        return result;
    }, {});
}

translations.TR = mergeTranslations(translations.EN, {
    nav: { games: "Oyunlar", topUps: "Bakiye", marketplace: "Pazar", tournaments: "Turnuvalar", search: "Oyun ara", language: "Dil", wishlist: "İstek listesi", cart: "Sepet", profile: "Profil", home: "GameSphere ana sayfa" },
    common: { loading: "Yükleniyor...", reset: "Sıfırla", clearAll: "Tümünü temizle", visitStore: "Mağazaya git", unknown: "Bilinmiyor", global: "Global", games: "oyun", products: "ürün", packages: "paket", lowestPrice: "En düşük fiyat", noOffers: "Seçilen filtrelere uygun teklif yok.", storeUnavailable: "Mağaza kullanılamıyor" },
    home: { eyebrow: "OYUN FİYAT KARŞILAŞTIRMASI", title: "Doğru platformda doğru oyunu bul.", description: "Resmi mağaza tekliflerini, platform sürümlerini ve dijital teslimat seçeneklerini tek katalogda karşılaştır.", browse: "Oyunlara göz at", marketplace: "Pazarı keşfet", what: "NELER YAPABİLİRSİN", heading: "Sonraki oyununa giden daha net yol.", compare: "Oyunları karşılaştır", compareText: "Tür, platform ve çıkış yılına göre ara.", items: "Pazar ürünlerini incele", itemsText: "Harici item pazarlarını ve sağlayıcıları incele.", follow: "Turnuvaları takip et", followText: "Rekabetçi etkinlikleri tek yerde tut.", featured: "Öne çıkan", featuredEyebrow: "MAĞAZALARDA FİYAT KONTROLÜ", comparePrices: "Fiyatları karşılaştır", compareOffers: "Teklifleri karşılaştır", viewOffers: "Tekliflere bak", viewAll: "Tümünü gör", from: "Başlayan fiyat", gameStore: "Oyun mağazası", catalogEyebrow: "KATALOG", trending: "Trend oyunlar", dealsEyebrow: "AKILLI ALIŞVERİŞ", bestDeals: "En iyi fırsatlar", platformEyebrow: "PLATFORMANI SEÇ", browsePlatforms: "Platforma göre göz at", tournamentEyebrow: "REKABET", tournaments: "Canlı ve yaklaşan turnuvalar", upcomingBadge: "Yaklaşan", prizePool: "ödül havuzu", digitalEyebrow: "DİJİTAL MAĞAZA", digitalStore: "Bakiye ve dijital ürünler", digitalProduct: "Dijital ürün", confirmPurchase: "Satın almayı onayla", continueBuy: "Devam et", recharge: "Oyun hesabına bakiye yükle", rechargeText: "Favori oyunların için oyun para birimi ve dijital paketleri bul." },
    games: { catalog: "Oyun kataloğu", browse: "Oyunlara göz at", resultsFor: "Sonuçlar", description: "Platformları, mağaza fiyatlarını ve dijital teklifleri karşılaştır.", showing: "{total} oyundan {count} gösteriliyor", loading: "Oyunlar yükleniyor...", previous: "Önceki", page: "Sayfa {current} / {total}", next: "Sonraki", filters: "Filtreler", gameType: "Oyun türü", allGames: "Tüm oyunlar", freeToPlay: "Ücretsiz oyunlar", paid: "Ücretli oyunlar", genre: "Tür", allGenres: "Tüm türler", platform: "Platform", allPlatforms: "Tüm platformlar", releaseYear: "Çıkış yılı", allYears: "Tüm yıllar", publisher: "Yayıncı", publisherPlaceholder: "Örneğin: EA", minPrice: "Min fiyat", maxPrice: "Maks fiyat", sortBy: "Sıralama", alphabetical: "Alfabetik", newest: "En yeni", oldest: "En eski", lowHigh: "Fiyat: düşükten yükseğe", highLow: "Fiyat: yüksekten düşüğe", apply: "Filtreleri uygula", noResults: "Oyun bulunamadı", tryFilters: "Filtreleri veya arama terimini değiştir.", resetFilters: "Filtreleri sıfırla", viewOffers: "Teklifleri gör", unknownDeveloper: "Bilinmeyen geliştirici", unknownPublisher: "Bilinmeyen yayıncı", tba: "Belirtilmedi", activeFilters: "Aktif filtreler", searchPrefix: "Arama: {value}", fromPrice: "${value} ve üzeri", upToPrice: "${value} kadar" },
    topUps: { eyebrow: "OYNAMASI ÜCRETSİZ EKONOMİ", title: "Bakiye yükleme", description: "Oyun para birimlerini, pass'leri ve dijital paketleri karşılaştır.", available: "{count} oyun mevcut", categories: { all: "Tüm yüklemeler", game: "Oyun yüklemeleri", gift: "Hediye kartları", subscription: "Abonelikler", credit: "Dijital krediler" }, loading: "Yüklemeler yükleniyor...", emptyTitle: "Henüz yükleme ürünü yok", emptyText: "Postman'dan oyun para birimi ürünü oluştur; burada görünsün.", packageEyebrow: "YÜKLEME PAKETLERİ", choose: "Bir paket seç ve seçilen sağlayıcıya devam et.", loadingPackages: "Paketler yükleniyor...", openCatalog: "Bu sayfayı Yüklemeler kataloğundan aç", packagesListed: "Katalog yüklendikten sonra paketler burada listelenir." },
    marketplace: { eyebrow: "DİJİTAL PAZAR", title: "Pazar", description: "Oyun anahtarlarını, DLC'leri, sürümleri, skin'leri ve dijital ürünleri karşılaştır.", products: "{count} ürün", loading: "Pazar yükleniyor...", emptyTitle: "Henüz pazar ürünü yok", emptyText: "catalogSection MARKETPLACE olan bir ürün oluştur." },
    errors: { notFound: "Sayfa bulunamadı", returnGames: "Oyunlara dön" },
});
translations.RU = mergeTranslations(translations.EN, {
    nav: { games: "Игры", topUps: "Пополнения", marketplace: "Маркетплейс", tournaments: "Турниры", search: "Поиск игр", language: "Язык", wishlist: "Избранное", cart: "Корзина", profile: "Профиль", home: "Главная GameSphere" },
    common: { loading: "Загрузка...", reset: "Сбросить", clearAll: "Очистить всё", visitStore: "Открыть магазин", unknown: "Неизвестно", global: "Глобальный", games: "игр", products: "товаров", packages: "пакетов", lowestPrice: "Самая низкая цена", noOffers: "Нет предложений по выбранным фильтрам.", storeUnavailable: "Магазин недоступен", close: "Закрыть", cancel: "Отмена", price: "Цена" },
    home: { eyebrow: "СРАВНЕНИЕ ЦЕН НА ИГРЫ", title: "Найдите нужную игру на нужной платформе.", description: "Сравнивайте официальные магазины, версии для платформ и варианты цифровой доставки в одном каталоге.", browse: "Смотреть игры", marketplace: "Открыть маркетплейс", what: "ЧТО МОЖНО СДЕЛАТЬ", heading: "Понятный путь к следующей игре.", compare: "Сравнить игры", compareText: "Ищите по жанру, платформе и году выпуска.", items: "Посмотреть товары", itemsText: "Изучайте внешние рынки предметов и поставщиков.", follow: "Следить за турнирами", followText: "Держите соревновательные события в одном месте.", featured: "Рекомендуем", featuredEyebrow: "ЦЕНЫ ПРОВЕРЕНЫ В МАГАЗИНАХ", comparePrices: "Сравнить цены", compareOffers: "Сравнить предложения", viewOffers: "Смотреть предложения", viewAll: "Смотреть все", from: "От", gameStore: "Магазин игр", catalogEyebrow: "КАТАЛОГ", trending: "Популярные игры", dealsEyebrow: "ВЫГОДНАЯ ПОКУПКА", bestDeals: "Лучшие предложения", platformEyebrow: "ВЫБЕРИТЕ ПЛАТФОРМУ", browsePlatforms: "По платформам", tournamentEyebrow: "СОРЕВНОВАНИЯ", tournaments: "Текущие и будущие турниры", upcomingBadge: "Скоро", prizePool: "призовой фонд", digitalEyebrow: "ЦИФРОВОЙ МАГАЗИН", digitalStore: "Пополнения и цифровые товары", digitalProduct: "Цифровой товар", confirmPurchase: "Подтвердите покупку", continueBuy: "Продолжить", recharge: "Пополняйте игровые аккаунты", rechargeText: "Находите игровую валюту и цифровые пакеты для любимых игр." },
    games: { catalog: "Каталог игр", browse: "Каталог игр", resultsFor: "Результаты", description: "Сравнивайте платформы, цены магазинов и цифровые предложения.", showing: "Показано {count} из {total} игр", loading: "Загрузка игр...", previous: "Назад", page: "Страница {current} из {total}", next: "Далее", filters: "Фильтры", gameType: "Тип игры", allGames: "Все игры", freeToPlay: "Бесплатные игры", paid: "Платные игры", genre: "Жанр", allGenres: "Все жанры", platform: "Платформа", allPlatforms: "Все платформы", releaseYear: "Год выпуска", allYears: "Все годы", publisher: "Издатель", publisherPlaceholder: "Например: EA", minPrice: "Мин. цена", maxPrice: "Макс. цена", sortBy: "Сортировка", alphabetical: "По алфавиту", newest: "Сначала новые", oldest: "Сначала старые", lowHigh: "Цена: по возрастанию", highLow: "Цена: по убыванию", apply: "Применить фильтры", noResults: "Игры не найдены", tryFilters: "Измените фильтры или поисковый запрос.", resetFilters: "Сбросить фильтры", viewOffers: "Смотреть предложения", unknownDeveloper: "Неизвестный разработчик", unknownPublisher: "Неизвестный издатель", tba: "Не указано", activeFilters: "Активные фильтры", searchPrefix: "Поиск: {value}", fromPrice: "От ${value}", upToPrice: "До ${value}" },
    topUps: { eyebrow: "ЭКОНОМИКА БЕСПЛАТНЫХ ИГР", title: "Пополнения", description: "Сравнивайте валюту, пропуски и цифровые пакеты для игр.", available: "Доступно игр: {count}", categories: { all: "Все пополнения", game: "Игровые пополнения", gift: "Подарочные карты", subscription: "Подписки", credit: "Цифровые кредиты" }, loading: "Загрузка пополнений...", emptyTitle: "Пока нет товаров для пополнения", emptyText: "Создайте товар игровой валюты в Postman, и он появится здесь.", packageEyebrow: "ПАКЕТЫ ПОПОЛНЕНИЯ", choose: "Выберите пакет и перейдите к выбранному поставщику.", loadingPackages: "Загрузка пакетов...", openCatalog: "Откройте эту страницу из каталога пополнений", packagesListed: "Пакеты появятся здесь после загрузки каталога." },
    marketplace: { eyebrow: "ЦИФРОВОЙ РЫНОК", title: "Маркетплейс", description: "Сравнивайте ключи игр, DLC, издания, скины и цифровые предметы.", products: "Товаров: {count}", loading: "Загрузка маркетплейса...", emptyTitle: "Пока нет товаров маркетплейса", emptyText: "Создайте товар с catalogSection MARKETPLACE." },
    errors: { notFound: "Страница не найдена", returnGames: "Вернуться к играм" },
});

const LanguageContext = createContext(null);

function getValue(source, path) {
    return path.split(".").reduce((value, key) => value?.[key], source);
}

function interpolate(value, variables) {
    return value.replace(/\{(\w+)\}/g, (_, key) => variables[key] ?? `{${key}}`);
}

export function I18nProvider({ children }) {
    const [language, setLanguageState] = useState(
        () => window.localStorage.getItem("gamesphere-language") || "EN",
    );

    function setLanguage(nextLanguage) {
        const safeLanguage = translations[nextLanguage] ? nextLanguage : "EN";
        setLanguageState(safeLanguage);
        window.localStorage.setItem("gamesphere-language", safeLanguage);
    }

    const value = useMemo(() => ({
        language,
        setLanguage,
        t(path, variables = {}) {
            const value = getValue(translations[language], path) ?? getValue(translations.EN, path) ?? path;
            return typeof value === "string" ? interpolate(value, variables) : value;
        },
    }), [language]);

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

// eslint-disable-next-line react-refresh/only-export-components
export function useTranslation() {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useTranslation must be used inside I18nProvider");
    return context;
}
